name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'docs/**'
      - '*.md'

jobs:
  setup-dependencies:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16, 18, 20]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - run: pnpm fetch

  tests:
    needs: setup-dependencies
    runs-on: ${{matrix.os}}
    timeout-minutes: 20
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16, 18, 20]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: "pnpm"
      - uses: pnpm/action-setup@v2.4.0
      - run: docker-compose up -d
      - run: pnpm install
      - run: sleep 10
      - run: pnpm test
